### PR TITLE
stats: fix don't report 4xx errors to sentry. closes #299

### LINKED ISSUE #299: Bad requests shouldn't create Sentry errors
https://github.com/filecoin-station/spark-stats/pull/293#issuecomment-2618097675

The reason for this Sentry error was a bad client request, which is a client error and not a server error, and therefore shouldn't be logged to Sentry.

### PR DESCRIPTION
**Pull request by juliangruber**
Closes #299

### CODE REVIEW

File: stats/lib/instrument.js [hunk 1]
```diff
@@ -26,5 +26,16 @@ Sentry.init({
   ],
   tracesSampleRate: 0.1,
   // Set sampling rate for performance profiling. This is relative to tracesSampleRate.
-  profilesSampleRate: 1.0
+  profilesSampleRate: 1.0,
+  // Ignore Fastify 4xx errors
+  // Remove once https://github.com/getsentry/sentry-javascript/pull/13198 lands
```
Comment (NikolasHaimerl) [inline stats/lib/instrument.js:31]: Are we tracking the removal somewhere too?

**Review by bajtos — APPROVED** [review]
LGTM, nice find!

Please remember to fix other projects using Fastify + Sentry combo.
